-- DravaInt production schema (Supabase / PostgreSQL 15+)
-- Safe to run repeatedly in the Supabase SQL editor.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  if to_jsonb(new) ? 'version' then new.version = coalesce(old.version, 0) + 1; end if;
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  email text unique,
  role text not null default 'workers' check (role in ('admin','boss','managers','level between admin and managers','workers')),
  rfid_code text unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_auth_user()
returns trigger security definer set search_path = public language plpgsql as $$
begin
  insert into public.profiles (id, username, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    new.email,
    coalesce(new.raw_user_meta_data ->> 'role', 'workers')
  ) on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email on auth.users
for each row execute function public.handle_new_auth_user();

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text unique not null,
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.roles (name) values
  ('admin'), ('boss'), ('managers'), ('level between admin and managers'), ('workers'),
  ('Alatničar'), ('Pomoćni alatničar'), ('CNC Operater'), ('CNC Programer')
on conflict (name) do nothing;

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name_hr text unique not null,
  name_en text unique not null,
  is_active boolean not null default true
);

insert into public.departments (name_hr, name_en) values
  ('Alatnica','Toolshop'), ('Brizganje','Injection moulding'), ('Montaža','Assembly'), ('Kontrola kvalitete','Quality assurance')
on conflict (name_hr) do nothing;

create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text unique,
  role_id bigint references public.roles(id) on delete set null,
  app_user_id uuid unique references auth.users(id) on delete set null,
  department_id bigint references public.departments(id) on delete set null,
  is_active boolean not null default true,
  status text not null default 'available' check (status in ('available','busy','break','absent')),
  qualifications text[] not null default '{}',
  calendar_token uuid unique not null default gen_random_uuid(),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.link_worker_to_profile()
returns trigger security definer set search_path = public language plpgsql as $$
begin
  update public.workers set app_user_id = new.id, updated_at = now()
  where lower(email) = lower(new.email) and app_user_id is null;
  return new;
end;
$$;
drop trigger if exists link_worker_after_profile on public.profiles;
create trigger link_worker_after_profile after insert or update of email on public.profiles
for each row execute function public.link_worker_to_profile();

create or replace function public.suspend_linked_auth_user()
returns trigger security definer set search_path = public, auth language plpgsql as $$
begin
  if old.is_active is distinct from new.is_active and new.app_user_id is not null then
    update auth.users set banned_until = case when new.is_active then null else now() + interval '100 years' end where id = new.app_user_id;
  end if;
  return new;
end;
$$;
drop trigger if exists worker_suspension_auth on public.workers;
create trigger worker_suspension_auth after update of is_active on public.workers for each row execute function public.suspend_linked_auth_user();

create table if not exists public.machines (
  id bigint generated by default as identity primary key,
  name text unique not null,
  type text not null check (type in ('mill','lathe','saw','qa','other')),
  axis int check (axis is null or axis in (3,4,5)),
  department_id bigint references public.departments(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.worker_qualifications (
  worker_id bigint not null references public.workers(id) on delete cascade,
  machine_id bigint not null references public.machines(id) on delete cascade,
  valid_until date,
  notes text,
  primary key (worker_id, machine_id)
);

create table if not exists public.shift_definitions (
  id bigint generated by default as identity primary key,
  department_id bigint references public.departments(id) on delete cascade,
  name_hr text not null,
  name_en text not null,
  start_time time not null,
  end_time time not null,
  color_code text not null default '#2563eb' check (color_code ~ '^#[0-9A-Fa-f]{6}$'),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique nulls not distinct (department_id, name_en)
);

insert into public.shift_definitions (name_hr,name_en,start_time,end_time,color_code) values
  ('Prva smjena','First shift','06:00','14:00','#2563eb'),
  ('Druga smjena','Second shift','14:00','22:00','#7c3aed'),
  ('Treća smjena','Third shift','22:00','06:00','#0f766e')
on conflict (department_id, name_en) do nothing;

create table if not exists public.rotation_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  department_id bigint references public.departments(id) on delete cascade,
  cycle_weeks int not null check (cycle_weeks between 1 and 52),
  pattern jsonb not null default '[]',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.shift_schedules (
  id bigint generated by default as identity primary key,
  week_number int not null check (week_number between 1 and 53),
  year int not null check (year between 2000 and 9999),
  start_date date not null,
  end_date date not null check (end_date >= start_date),
  department text not null default 'Alatnica',
  department_id bigint references public.departments(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  modified_by uuid references auth.users(id) on delete set null default auth.uid(),
  status text not null default 'draft' check (status in ('draft','published')),
  version int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (week_number, year, department)
);

create table if not exists public.shift_assignments (
  id bigint generated by default as identity primary key,
  shift_schedule_id bigint not null references public.shift_schedules(id) on delete cascade,
  worker_id bigint not null references public.workers(id) on delete cascade,
  shift_definition_id bigint not null references public.shift_definitions(id),
  date date not null,
  is_override boolean not null default false,
  notes text not null default '',
  version int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shift_schedule_id, worker_id, date)
);

create table if not exists public.absences (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references public.workers(id) on delete cascade,
  start_date date not null,
  end_date date not null check (end_date >= start_date),
  type text not null check (type in ('vacation','sick','training','maternity','other')),
  notes text not null default '',
  approved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  machine text not null default '',
  machine_id bigint references public.machines(id) on delete set null,
  job_order text not null,
  product_description text not null default '',
  operator text not null default '',
  operator_id bigint references public.workers(id) on delete set null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  status text not null default 'planned' check (status in ('planned','inProgress','done','delayed')),
  progress int not null default 0 check (progress between 0 and 100),
  color text not null default '#2563eb',
  operations jsonb,
  dependencies jsonb,
  parent_id bigint references public.jobs(id) on delete set null,
  comments text not null default '',
  setup_hours numeric(8,2) not null default 0,
  material_status text not null default 'ready' check (material_status in ('ready','waiting','delayed')),
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  version int not null default 1,
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_time >= start_time)
);

create index if not exists jobs_machine_time_idx on public.jobs(machine,start_time,end_time) where deleted_at is null;
create index if not exists jobs_operator_time_idx on public.jobs(operator_id,start_time,end_time) where deleted_at is null;
create index if not exists shift_assignments_worker_date_idx on public.shift_assignments(worker_id,date);
create index if not exists absences_worker_dates_idx on public.absences(worker_id,start_date,end_date);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.app_settings (key,value) values
  ('shift_hours','8'), ('max_weekly_hours','48'), ('minimum_rest_hours','12'), ('workday','{"start":6,"end":22}')
on conflict (key) do nothing;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null default auth.uid(),
  action text not null,
  target_table text not null,
  record_id text,
  before_state jsonb,
  after_state jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.audit_row_change()
returns trigger security definer set search_path = public language plpgsql as $$
begin
  insert into public.audit_logs(action,target_table,record_id,before_state,after_state)
  values (tg_op,tg_table_name,coalesce((to_jsonb(new)->>'id'),(to_jsonb(old)->>'id')),case when tg_op='INSERT' then null else to_jsonb(old) end,case when tg_op='DELETE' then null else to_jsonb(new) end);
  return coalesce(new,old);
end;
$$;

do $$ declare table_name text; begin
  foreach table_name in array array['workers','roles','machines','jobs','shift_definitions','shift_schedules','shift_assignments','absences'] loop
    execute format('drop trigger if exists audit_%I on public.%I',table_name,table_name);
    execute format('create trigger audit_%I after insert or update or delete on public.%I for each row execute function public.audit_row_change()',table_name,table_name);
  end loop;
end $$;
drop policy if exists authenticated_read on public.audit_logs;

do $$ declare table_name text; begin
  foreach table_name in array array['profiles','roles','workers','machines','jobs','shift_schedules','shift_assignments'] loop
    execute format('drop trigger if exists updated_at_%I on public.%I',table_name,table_name);
    execute format('create trigger updated_at_%I before update on public.%I for each row execute function public.set_updated_at()',table_name,table_name);
  end loop;
end $$;

-- LIMITATION (improvements-plan item #10, server side): this guard compares `machine` by exact
-- string and evaluates a single tstzrange per row. Routed orders carry a zero-duration parent
-- window (their real work lives in the `operations` JSONB), so this trigger neither protects nor
-- false-flags them — DB-level double-booking is effectively unenforced for routed work. A correct
-- fix requires modelling operations as rows (a job_operations table, item #13); the client-side
-- cpm.getJobConflicts() already covers routed overlaps in the meantime.
create or replace function public.validate_job_assignment()
returns trigger language plpgsql as $$
begin
  if new.deleted_at is not null or new.status = 'done' then return new; end if;
  if new.machine <> '' and exists(select 1 from public.jobs j where j.id <> coalesce(new.id,0) and j.deleted_at is null and j.status <> 'done' and j.machine = new.machine and tstzrange(j.start_time,j.end_time,'[)') && tstzrange(new.start_time,new.end_time,'[)')) then
    raise exception 'Machine % is already allocated in this time range', new.machine using errcode = 'DR001';
  end if;
  if new.operator_id is not null and exists(select 1 from public.jobs j where j.id <> coalesce(new.id,0) and j.deleted_at is null and j.status <> 'done' and j.operator_id = new.operator_id and tstzrange(j.start_time,j.end_time,'[)') && tstzrange(new.start_time,new.end_time,'[)')) then
    raise exception 'Operator is already allocated in this time range' using errcode = 'DR001';
  end if;
  return new;
end;
$$;
drop trigger if exists validate_job_assignment_trigger on public.jobs;
create constraint trigger validate_job_assignment_trigger after insert or update of machine,operator_id,start_time,end_time,status on public.jobs deferrable initially deferred for each row execute function public.validate_job_assignment();

create or replace function public.notify_shift_change()
returns trigger language plpgsql as $$
begin
  perform pg_notify('shift_changes', json_build_object('table',tg_table_name,'operation',tg_op,'id',coalesce(new.id,old.id))::text);
  return coalesce(new,old);
end;
$$;
drop trigger if exists shift_assignment_notify on public.shift_assignments;
create trigger shift_assignment_notify after insert or update or delete on public.shift_assignments for each row execute function public.notify_shift_change();

create or replace function public.generate_shift_schedule(p_start_date date,p_week_count int,p_worker_ids bigint[],p_department text default 'Alatnica')
returns setof public.shift_schedules security definer set search_path = public language plpgsql as $$
declare week_index int; day_index int; worker_index int; schedule_row public.shift_schedules; definitions bigint[]; worker_id bigint; target_date date;
begin
  select array_agg(id order by start_time) into definitions from public.shift_definitions where is_active;
  if definitions is null or array_length(definitions,1)=0 then raise exception 'No active shift definitions'; end if;
  for week_index in 0..least(greatest(p_week_count,1),52)-1 loop
    target_date := p_start_date + week_index * 7;
    insert into public.shift_schedules(week_number,year,start_date,end_date,department,status,created_by,modified_by)
    values (extract(week from target_date)::int,extract(year from target_date)::int,target_date,target_date+6,p_department,'draft',auth.uid(),auth.uid())
    on conflict (week_number,year,department) do update set start_date=excluded.start_date,end_date=excluded.end_date,modified_by=auth.uid()
    returning * into schedule_row;
    for day_index in 0..4 loop
      for worker_index in 1..coalesce(array_length(p_worker_ids,1),0) loop
        worker_id := p_worker_ids[worker_index];
        if not exists(select 1 from public.absences a where a.worker_id=worker_id and target_date+day_index between a.start_date and a.end_date) then
          insert into public.shift_assignments(shift_schedule_id,worker_id,shift_definition_id,date,is_override)
          values(schedule_row.id,worker_id,definitions[1+mod(worker_index-1+week_index,array_length(definitions,1))],target_date+day_index,false)
          on conflict (shift_schedule_id,worker_id,date) do update set shift_definition_id=excluded.shift_definition_id where public.shift_assignments.is_override=false;
        end if;
      end loop;
    end loop;
    return next schedule_row;
  end loop;
end;
$$;

create or replace view public.machine_load_metrics with (security_invoker=true) as
select machine,date_trunc('week',start_time) week_start,count(*) job_count,sum(extract(epoch from (end_time-start_time))/3600) active_hours
from public.jobs where deleted_at is null group by machine,date_trunc('week',start_time);

create or replace view public.operator_load_metrics with (security_invoker=true) as
select operator_id,date_trunc('week',start_time) week_start,count(*) job_count,sum(extract(epoch from (end_time-start_time))/3600) active_hours
from public.jobs where deleted_at is null and operator_id is not null group by operator_id,date_trunc('week',start_time);

create or replace function public.current_app_role() returns text stable security definer set search_path = public language sql as $$ select role from public.profiles where id=auth.uid() and is_active $$;

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb stable language plpgsql as $$
declare claims jsonb; app_role text;
begin
  select role into app_role from public.profiles where id=(event->>'user_id')::uuid;
  claims := event->'claims';
  claims := jsonb_set(claims,'{app_role}',to_jsonb(coalesce(app_role,'workers')));
  return jsonb_set(event,'{claims}',claims);
end;
$$;

alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.departments enable row level security;
alter table public.workers enable row level security;
alter table public.machines enable row level security;
alter table public.worker_qualifications enable row level security;
alter table public.shift_definitions enable row level security;
alter table public.rotation_templates enable row level security;
alter table public.shift_schedules enable row level security;
alter table public.shift_assignments enable row level security;
alter table public.absences enable row level security;
alter table public.jobs enable row level security;
alter table public.app_settings enable row level security;
alter table public.audit_logs enable row level security;

-- NOTE: audit_logs is deliberately excluded here. It holds before/after row images of every
-- table and must stay admin-only (see audit_admin_read below). Adding it to this read-all loop
-- would OR an unrestricted `using (true)` select policy on top of audit_admin_read and expose the
-- full audit trail to every worker. absences is also excluded: its health-sensitive columns are
-- masked via the public.absences_visible view (GDPR); direct table select is revoked below.
do $$ declare table_name text; begin
  foreach table_name in array array['profiles','roles','departments','workers','machines','worker_qualifications','shift_definitions','rotation_templates','shift_schedules','shift_assignments','jobs','app_settings'] loop
    execute format('drop policy if exists authenticated_read on public.%I',table_name);
    execute format('create policy authenticated_read on public.%I for select to authenticated using (true)',table_name);
  end loop;
end $$;

drop policy if exists profile_self_update on public.profiles;
create policy profile_self_update on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());

do $$ declare table_name text; begin
  foreach table_name in array array['roles','departments','workers','machines','worker_qualifications','shift_definitions','rotation_templates','app_settings'] loop
    execute format('drop policy if exists admin_write on public.%I',table_name);
    execute format('create policy admin_write on public.%I for all to authenticated using (public.current_app_role() in (''admin'',''boss'')) with check (public.current_app_role() in (''admin'',''boss''))',table_name);
  end loop;
  foreach table_name in array array['shift_schedules','shift_assignments','absences','jobs'] loop
    execute format('drop policy if exists planner_write on public.%I',table_name);
    execute format('create policy planner_write on public.%I for all to authenticated using (public.current_app_role() in (''admin'',''boss'',''managers'',''level between admin and managers'')) with check (public.current_app_role() in (''admin'',''boss'',''managers'',''level between admin and managers''))',table_name);
  end loop;
end $$;

drop policy if exists worker_progress_update on public.jobs;
create policy worker_progress_update on public.jobs for update to authenticated using (operator_id in (select id from public.workers where app_user_id=auth.uid())) with check (operator_id in (select id from public.workers where app_user_id=auth.uid()));
drop policy if exists audit_admin_read on public.audit_logs;
create policy audit_admin_read on public.audit_logs for select to authenticated using (public.current_app_role() in ('admin','boss'));

-- ---------------------------------------------------------------------------
-- Column-level credential hardening (RLS is row-level only; PostgREST honours
-- column privileges, so we revoke table-level SELECT and re-grant safe columns).
--   * profiles.rfid_code   — a badge is an authentication credential; a logged-in
--                            worker must not be able to enumerate everyone's badges.
--   * workers.calendar_token — a capability token for the shift-calendar feed.
-- Admin management of these values happens through the service-role edge
-- functions (admin-users, shift-calendar), which bypass these grants.
revoke select on public.profiles from authenticated;
grant select (id, username, email, role, is_active, created_at, updated_at) on public.profiles to authenticated;
revoke select on public.workers from authenticated;
grant select (id, first_name, last_name, email, role_id, app_user_id, department_id, is_active, status, qualifications, deleted_at, created_at, updated_at) on public.workers to authenticated;

-- ---------------------------------------------------------------------------
-- Absence health data (GDPR): `type` (sick/maternity/…) and `notes` are sensitive.
-- Direct table SELECT is revoked; everyone reads through this masking view, which
-- reveals type/notes only to planners/admin and nulls them for ordinary workers
-- (who still need worker + date range for the "today's absence" alert). The view
-- is SECURITY DEFINER (owner-run) so it can read the base table after the revoke.
revoke select on public.absences from authenticated;
create or replace view public.absences_visible with (security_barrier=true) as
  select
    a.id,
    a.worker_id,
    a.start_date,
    a.end_date,
    case when public.current_app_role() in ('admin','boss','managers','level between admin and managers') then a.type else null end as type,
    case when public.current_app_role() in ('admin','boss','managers','level between admin and managers') then a.notes else '' end as notes,
    a.approved_by,
    a.created_at
  from public.absences a;
grant select on public.absences_visible to authenticated;

do $$ declare table_name text; begin
  foreach table_name in array array['profiles','roles','workers','machines','jobs','shift_definitions','shift_schedules','shift_assignments','absences'] loop
    begin execute format('alter publication supabase_realtime add table public.%I',table_name); exception when duplicate_object then null; end;
  end loop;
end $$;

-- Legacy plaintext table is deliberately disabled if it exists.
do $$ begin
  if to_regclass('public.app_users') is not null then
    execute 'revoke all on public.app_users from anon, authenticated';
    execute 'comment on table public.app_users is ''DEPRECATED: use Supabase Auth and public.profiles''';
  end if;
end $$;
