-- Run this once in your Supabase project's SQL Editor (Database > SQL Editor > New query).
-- Creates the tables the app needs and opens them up to the anon key,
-- since this app manages its own simple username/password login instead
-- of using Supabase Auth.

create table if not exists app_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  created_at timestamptz not null default now()
);

insert into app_users (username, password)
values ('dturk', '1234')
on conflict (username) do nothing;

create table if not exists app_settings (
  key text primary key,
  value text
);

create table if not exists jobs (
  id bigint generated by default as identity primary key,
  machine text not null default '',
  job_order text not null default '',
  operator text not null default '',
  start_time text not null default '',
  end_time text not null default '',
  status text not null default 'planned',
  progress int not null default 0,
  color text not null default '#1a365d',
  operations jsonb,
  created_at timestamptz not null default now()
);

-- Row level security: enabled but with permissive policies for the anon key,
-- since access control is handled in the app itself (simple username/password
-- gate), not via Supabase Auth. This is fine for a small internal tool but
-- means anyone with the anon key can read/write these tables directly.
alter table app_users enable row level security;
alter table app_settings enable row level security;
alter table jobs enable row level security;

create policy "allow all app_users" on app_users for all using (true) with check (true);
create policy "allow all app_settings" on app_settings for all using (true) with check (true);
create policy "allow all jobs" on jobs for all using (true) with check (true);

-- Enable realtime so changes made on one device show up on others live.
alter publication supabase_realtime add table app_users;
alter publication supabase_realtime add table app_settings;
alter publication supabase_realtime add table jobs;
