-- 0008: Phase D — operations as rows (public.job_operations) + warn-then-enforce DB-level overlap.
--
-- Until now a routed order's per-step work lived ONLY in the jobs.operations JSONB. The DB could not
-- enforce machine double-booking for routed work: validate_job_assignment() compared the single
-- jobs.machine text (a display chain like "Pila → CNC-1 → …" for routed orders) over the job's
-- zero-duration parent window, so it neither protected nor false-flagged routed operations
-- (see the LIMITATION comment in schema.sql and IMPROVEMENTS_PLAN item #13).
--
-- This migration:
--   1. Creates public.job_operations (one row per operation) with the full live-Supabase new-table
--      checklist: explicit grants, RLS mirroring jobs, realtime publication.
--   2. Installs sync_job_operations(): a SECURITY DEFINER trigger that keeps job_operations in sync
--      with jobs.operations on every write. The JSONB stays the client write format; the rows are a
--      derived mirror. This IS the dual-write — every existing client path (updateJob/addJob/
--      WorkOrderCreator/board lane-move) writes both copies atomically, with no client change.
--   3. Backfills job_operations from existing JSONB, with a per-job checksum (rows == JSONB length).
--   4. Extends validate_job_assignment() with an operation-level overlap check that expands routed
--      jobs into sequential per-machine windows (via the job_effective_windows view) and compares them
--      against every other active job's windows. It starts in WARN mode (logs to audit_logs, allows
--      the write); flipping public.app_settings 'job_operations_overlap_enforcement' to '"enforce"'
--      makes it reject with errcode DR001 (the same code the client already handles as 'rejected').
--
-- SAFETY:
--   * Additive + idempotent. Re-running is safe (create if not exists, on-conflict upserts,
--     create-or-replace functions). The JSONB remains authoritative; nothing reads job_operations for
--     display yet — rollback = stop reading rows / set enforcement back to warn (see MACHINE_OPERATIONS_ROLLOUT.md).
--   * The sync trigger never rejects a jobs write the JSONB already accepted (hours clamped >= 0,
--     empty machine allowed). Enforcement is opt-in and defaults to warn.
--
-- REQUIRES A LIVE-DB SESSION TO APPLY. This was authored without production Supabase credentials and
-- has NOT been run against production. See MACHINE_OPERATIONS_ROLLOUT.md for the apply/verify steps.

begin;

------------------------------------------------------------------------------------------------------
-- 1) Table
------------------------------------------------------------------------------------------------------
create table if not exists public.job_operations (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  seq int not null,                                  -- 0-based index within jobs.operations
  name text not null default '',
  machine_id bigint references public.machines(id) on delete set null,
  machine_name text not null default '',             -- denormalized display (verbatim from JSONB)
  hours numeric not null default 0 check (hours >= 0),
  operator_id bigint references public.workers(id) on delete set null,
  operator_name text not null default '',
  created_at timestamptz not null default now(),
  unique (job_id, seq)
);

-- Per-machine queries on routed work (the whole point — jobs_machine_time_idx is useless for routed
-- orders because it indexes the display chain string). Plus a job_id index for the sync delete/reinsert.
create index if not exists job_operations_machine_idx on public.job_operations(machine_id);
create index if not exists job_operations_job_idx on public.job_operations(job_id);

------------------------------------------------------------------------------------------------------
-- 2) Grants + RLS (live-Supabase checklist: default privileges are unreliable on some projects, so
--    grant explicitly; the privilege check runs BEFORE RLS). Clients only READ job_operations for now
--    (the sync trigger, SECURITY DEFINER, owns all writes), so no insert/update/delete grant is needed.
------------------------------------------------------------------------------------------------------
grant select on public.job_operations to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.job_operations enable row level security;
drop policy if exists authenticated_read on public.job_operations;
create policy authenticated_read on public.job_operations for select to authenticated using (true);

-- Board live-update: publish to realtime (guarded — duplicate add is a no-op).
do $$ begin
  begin execute 'alter publication supabase_realtime add table public.job_operations'; exception when duplicate_object then null; end;
end $$;

-- NOTE: no audit trigger and no updated_at/version columns. job_operations is a *derived* mirror of
-- jobs.operations; the parent jobs row is already audited (schema.sql audit loop) and carries the
-- version. Auditing the derived rows too would only double the trail. If direct client writes to
-- job_operations are ever added (post-cutover), revisit this.

------------------------------------------------------------------------------------------------------
-- 3) Sync trigger: jobs.operations JSONB -> job_operations rows (the dual-write mechanism).
--    Mirrors src/scheduling/jobOperations.ts buildJobOperationRows() exactly (0-based seq, verbatim
--    id/name/hours/operator, hours clamped >= 0, every op emitted so count == jsonb_array_length).
------------------------------------------------------------------------------------------------------
create or replace function public.sync_job_operations()
returns trigger security definer set search_path = public language plpgsql as $$
begin
  -- Rebuild is delete-all + reinsert: simplest correct sync, and the row set per job is tiny.
  delete from public.job_operations where job_id = new.id;

  if new.operations is not null and jsonb_typeof(new.operations) = 'array' then
    insert into public.job_operations (job_id, seq, name, machine_id, machine_name, hours, operator_id, operator_name)
    select
      new.id,
      (op.ord - 1)::int,                                        -- 0-based, matches the TS mirror
      coalesce(op.value->>'name', ''),
      nullif(op.value->>'machineId', '')::bigint,
      btrim(coalesce(op.value->>'machine', '')),
      greatest(0, coalesce((op.value->>'hours')::numeric, 0)),  -- never negative
      nullif(op.value->>'operatorId', '')::bigint,
      btrim(coalesce(op.value->>'operator', ''))
    from jsonb_array_elements(new.operations) with ordinality as op(value, ord);
  end if;

  return new;
end;
$$;

-- Fire whenever the operations JSONB could have changed. INSERT always; UPDATE only when `operations`
-- is in the SET list (a start_time-only move doesn't change the rows — windows are derived, not stored).
drop trigger if exists sync_job_operations_trigger on public.jobs;
create trigger sync_job_operations_trigger
  after insert or update of operations on public.jobs
  for each row execute function public.sync_job_operations();

------------------------------------------------------------------------------------------------------
-- 4) One-time backfill of existing rows + checksum.
------------------------------------------------------------------------------------------------------
do $$
declare
  mismatch record;
  mismatch_count int := 0;
begin
  -- Rebuild every routed job's rows from its current JSONB (idempotent via the unique key).
  delete from public.job_operations jo
    using public.jobs j
    where jo.job_id = j.id
      and (j.operations is null or jsonb_typeof(j.operations) <> 'array');

  insert into public.job_operations (job_id, seq, name, machine_id, machine_name, hours, operator_id, operator_name)
  select
    j.id,
    (op.ord - 1)::int,
    coalesce(op.value->>'name', ''),
    nullif(op.value->>'machineId', '')::bigint,
    btrim(coalesce(op.value->>'machine', '')),
    greatest(0, coalesce((op.value->>'hours')::numeric, 0)),
    nullif(op.value->>'operatorId', '')::bigint,
    btrim(coalesce(op.value->>'operator', ''))
  from public.jobs j
  cross join lateral jsonb_array_elements(j.operations) with ordinality as op(value, ord)
  where j.operations is not null and jsonb_typeof(j.operations) = 'array'
  on conflict (job_id, seq) do update set
    name = excluded.name,
    machine_id = excluded.machine_id,
    machine_name = excluded.machine_name,
    hours = excluded.hours,
    operator_id = excluded.operator_id,
    operator_name = excluded.operator_name;

  -- Drop any stale rows beyond the current JSONB length (e.g. an operation was removed since a prior run).
  delete from public.job_operations jo
    using public.jobs j
    where jo.job_id = j.id
      and j.operations is not null and jsonb_typeof(j.operations) = 'array'
      and jo.seq >= jsonb_array_length(j.operations);

  -- Checksum: row count per routed job must equal its JSONB operation count.
  for mismatch in
    select j.id, j.job_order, jsonb_array_length(j.operations) as jsonb_len,
           (select count(*) from public.job_operations jo where jo.job_id = j.id) as row_count
    from public.jobs j
    where j.operations is not null and jsonb_typeof(j.operations) = 'array'
  loop
    if mismatch.jsonb_len <> mismatch.row_count then
      mismatch_count := mismatch_count + 1;
      raise warning 'job_operations checksum MISMATCH: job % (%): JSONB has % op(s), % row(s) written',
        mismatch.id, mismatch.job_order, mismatch.jsonb_len, mismatch.row_count;
    end if;
  end loop;

  if mismatch_count = 0 then
    raise notice 'Phase D backfill: job_operations in sync with jobs.operations for every routed job (checksum OK).';
  else
    raise warning 'Phase D backfill: % job(s) failed the checksum — investigate before enforcing.', mismatch_count;
  end if;
end $$;

------------------------------------------------------------------------------------------------------
-- 5) Machine-key resolver (mirrors src/scheduling/machineIdentity.ts resolveMachineId): prefer a live
--    id, else a case-insensitive name match, else fall back to the raw name. Two references to the same
--    machine — one by id, one by name — collapse to the same key so a rename doesn't hide a clash.
------------------------------------------------------------------------------------------------------
create or replace function public.machine_match_key(p_id bigint, p_name text)
returns text stable language sql as $$
  select case
    when p_id is not null and exists (select 1 from public.machines m where m.id = p_id) then 'id:' || p_id
    else coalesce(
      (select 'id:' || m.id from public.machines m
        where lower(btrim(m.name)) = lower(btrim(coalesce(p_name, ''))) order by m.id limit 1),
      'name:' || lower(btrim(coalesce(p_name, '')))
    )
  end
$$;

------------------------------------------------------------------------------------------------------
-- 6) Effective-window view (mirrors src/scheduling/jobOperations.ts expandJobEffectiveWindows):
--    routed ops laid out sequentially from the job start; plain single-machine jobs as one window.
--    Legacy chain-string jobs without operations are excluded (no trustworthy per-segment window).
------------------------------------------------------------------------------------------------------
create or replace view public.job_effective_windows with (security_invoker = true) as
-- Routed operations: sequential windows from jobs.start_time (cumulative op hours).
select
  jo.job_id,
  j.job_order,
  jo.seq,
  true as is_operation,
  public.machine_match_key(jo.machine_id, jo.machine_name) as machine_key,
  jo.machine_name,
  j.start_time
    + make_interval(secs => 3600 * coalesce(
        sum(jo.hours) over (partition by jo.job_id order by jo.seq
          rows between unbounded preceding and 1 preceding), 0)) as op_start,
  j.start_time
    + make_interval(secs => 3600 * sum(jo.hours) over (partition by jo.job_id order by jo.seq
          rows between unbounded preceding and current row)) as op_end
from public.job_operations jo
join public.jobs j on j.id = jo.job_id
where j.deleted_at is null
  and j.status <> 'done'
  and btrim(coalesce(jo.machine_name, '')) <> ''
  and jo.hours > 0
  -- exclude jobs that themselves have children (containers) — their leaves carry the work
  and not exists (select 1 from public.jobs c where c.parent_id = j.id and c.deleted_at is null)
union all
-- Plain single-machine jobs (no operations, machine is not a → chain): one window over the whole job.
select
  j.id,
  j.job_order,
  0 as seq,
  false as is_operation,
  public.machine_match_key(j.machine_id, j.machine) as machine_key,
  j.machine as machine_name,
  j.start_time as op_start,
  j.end_time as op_end
from public.jobs j
where j.deleted_at is null
  and j.status <> 'done'
  and (j.operations is null or jsonb_typeof(j.operations) <> 'array' or jsonb_array_length(j.operations) = 0)
  and position('→' in coalesce(j.machine, '')) = 0
  and btrim(coalesce(j.machine, '')) <> ''
  and j.end_time > j.start_time
  and not exists (select 1 from public.jobs c where c.parent_id = j.id and c.deleted_at is null);

------------------------------------------------------------------------------------------------------
-- 7) Overlap detector (mirrors detectOperationOverlaps): windows on the same machine that overlap in
--    time, where AT LEAST ONE side is a real routed operation. Plain-vs-plain is intentionally left to
--    the legacy jobs.machine string check in validate_job_assignment (already hard-enforced), so this
--    adds exactly the missing coverage (routed-vs-routed and routed-vs-plain) without double-flagging.
------------------------------------------------------------------------------------------------------
create or replace function public.detect_job_operation_overlaps(p_job_id bigint)
returns table (other_job_id bigint, other_order text, machine_name text, this_seq int, other_seq int)
stable language sql as $$
  select b.job_id, b.job_order, a.machine_name, a.seq, b.seq
  from public.job_effective_windows a
  join public.job_effective_windows b
    on b.job_id <> a.job_id
   and a.machine_key = b.machine_key
   and tstzrange(a.op_start, a.op_end, '[)') && tstzrange(b.op_start, b.op_end, '[)')
  where a.job_id = p_job_id
    and (a.is_operation or b.is_operation)
$$;

------------------------------------------------------------------------------------------------------
-- 8) Enforcement mode flag (default warn) + a SECURITY DEFINER warn-logger (audit_logs INSERT is
--    revoked from authenticated, so the client-invoked validate trigger cannot write it directly).
------------------------------------------------------------------------------------------------------
insert into public.app_settings (key, value) values ('job_operations_overlap_enforcement', '"warn"')
on conflict (key) do nothing;

create or replace function public.log_operation_overlap_warning(
  p_job_id bigint, p_machine text, p_other_order text, p_this_seq int, p_other_seq int)
returns void security definer set search_path = public language sql as $$
  insert into public.audit_logs (action, target_table, record_id, after_state)
  values ('operation_overlap_warning', 'jobs', p_job_id::text,
    jsonb_build_object('machine', p_machine, 'other_order', p_other_order,
                       'this_seq', p_this_seq, 'other_seq', p_other_seq));
$$;

------------------------------------------------------------------------------------------------------
-- 9) Extend validate_job_assignment: keep the existing plain-machine + operator string checks
--    (unchanged — plain-vs-plain stays hard-enforced), and ADD the routed operation-level check in
--    warn/enforce mode. The sync trigger above is a plain AFTER trigger, so it has already refreshed
--    job_operations by the time this DEFERRED constraint trigger evaluates at commit.
------------------------------------------------------------------------------------------------------
create or replace function public.validate_job_assignment()
returns trigger language plpgsql as $$
declare
  v_mode text;
  v_conflict record;
begin
  if new.deleted_at is not null or new.status = 'done' then return new; end if;

  -- Legacy plain-machine double-booking (exact string over the single job window). Unchanged.
  if new.machine <> '' and exists (
    select 1 from public.jobs j
    where j.id <> coalesce(new.id, 0) and j.deleted_at is null and j.status <> 'done'
      and j.machine = new.machine
      and tstzrange(j.start_time, j.end_time, '[)') && tstzrange(new.start_time, new.end_time, '[)')
  ) then
    raise exception 'Machine % is already allocated in this time range', new.machine using errcode = 'DR001';
  end if;

  -- Operator double-booking. Unchanged.
  if new.operator_id is not null and exists (
    select 1 from public.jobs j
    where j.id <> coalesce(new.id, 0) and j.deleted_at is null and j.status <> 'done'
      and j.operator_id = new.operator_id
      and tstzrange(j.start_time, j.end_time, '[)') && tstzrange(new.start_time, new.end_time, '[)')
  ) then
    raise exception 'Operator is already allocated in this time range' using errcode = 'DR001';
  end if;

  -- Phase D: routed operation-level overlap (warn-then-enforce). Picks up the FIRST conflicting pair.
  select o.other_order, o.machine_name, o.this_seq, o.other_seq
    into v_conflict
    from public.detect_job_operation_overlaps(new.id) o
    limit 1;

  if found then
    v_mode := coalesce((select value #>> '{}' from public.app_settings
                        where key = 'job_operations_overlap_enforcement'), 'warn');
    if v_mode = 'enforce' then
      raise exception 'Operation on % overlaps order % (step %/%)',
        v_conflict.machine_name, v_conflict.other_order, v_conflict.this_seq, v_conflict.other_seq
        using errcode = 'DR001';
    else
      -- warn-only: record to the audit trail and allow the write.
      perform public.log_operation_overlap_warning(
        new.id, v_conflict.machine_name, v_conflict.other_order, v_conflict.this_seq, v_conflict.other_seq);
      raise warning 'Operation on % overlaps order % — allowed (overlap enforcement = warn)',
        v_conflict.machine_name, v_conflict.other_order;
    end if;
  end if;

  return new;
end;
$$;

-- Recreate the constraint trigger with `operations` added to the column list, so an operations-only
-- edit (e.g. a board lane-move that only rewrites the JSONB) re-runs the overlap check.
drop trigger if exists validate_job_assignment_trigger on public.jobs;
create constraint trigger validate_job_assignment_trigger
  after insert or update of machine, operator_id, start_time, end_time, status, operations on public.jobs
  deferrable initially deferred for each row execute function public.validate_job_assignment();

commit;
